package com.securebank.user.enums;

public enum ChangeRequestType {
  UPDATE_PROFILE,
  UPDATE_NOTIFICATION_PREFERENCES,
  LINK_DEVICE,
  TRUST_DEVICE,
  REVOKE_DEVICE,
  ADMIN_UPDATE_ROLE,
  ADMIN_UPDATE_STATUS,
}
