server:
  port: 8086

spring:
  application:
    name: payments-service
  datasource:
    url: jdbc:postgresql://localhost:5432/securebank
    username: securebank
    password: securebank_secret_pass
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
