server:
  port: ${SERVER_PORT:8088}

spring:
  application:
    name: notification-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/securebank}
    username: ${SPRING_DATASOURCE_USERNAME:securebank}
    password: ${SPRING_DATASOURCE_PASSWORD:securebank_secret_pass}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: flyway_schema_history_notification
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        max.poll.interval.ms: 300000

jwt:
  secret: ${JWT_SECRET:dGhpc0lzQVZlcnlTZWN1cmVTZWNyZXRLZXlGb3JTZWN1cmVCYW5rSkdUVG9rZW5zMjAyNiE=}

notification:
  sms:
    enabled: ${NOTIFICATION_SMS_ENABLED:true}
    guaranteed-security-fallback: true
  email:
    enabled: ${NOTIFICATION_EMAIL_ENABLED:true}
  push:
    enabled: ${NOTIFICATION_PUSH_ENABLED:true}
