server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: accounts-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/securebank}
    username: ${SPRING_DATASOURCE_USERNAME:securebank}
    password: ${SPRING_DATASOURCE_PASSWORD:securebank_secret_pass}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: flyway_schema_history_accounts
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

totp-service:
  url: ${TOTP_SERVICE_URL:http://localhost:8082}

user-service:
  url: ${USER_SERVICE_URL:http://localhost:8083}
