apiVersion: v1
kind: ConfigMap
metadata:
  name: securebank-config
  namespace: securebank
data:
  SPRING_PROFILES_ACTIVE: "prod"
  POSTGRES_HOST: "securebank-postgres"
  POSTGRES_PORT: "5432"
  KAFKA_BOOTSTRAP_SERVERS: "securebank-kafka:9092"
  JWT_EXPIRATION_MS: "86400000"
---
apiVersion: v1
kind: Secret
metadata:
  name: securebank-secrets
  namespace: securebank
type: Opaque
stringData:
  POSTGRES_USER: "securebank"
  POSTGRES_PASSWORD: "securebank_prod_password"
  JWT_SECRET: "c2VjdXJlYmFua19zZWNyZXRfa2V5X2Zvcl9qd3RfdG9rZW5fZ2VuZXJhdGlvbl8yMDI2"
