apiVersion: v1
kind: ConfigMap
metadata:
  name: securebank-config
  namespace: securebank
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://securebank-postgres:5432/securebank"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
  SPRING_FLYWAY_BASELINE_VERSION: "0"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "securebank-kafka:9092"
  JWT_EXPIRATION_MS: "86400000"
---
apiVersion: v1
kind: Secret
metadata:
  name: securebank-secrets
  namespace: securebank
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "securebank"
  SPRING_DATASOURCE_PASSWORD: "securebank_prod_password"
  POSTGRES_USER: "securebank"
  POSTGRES_PASSWORD: "securebank_prod_password"
  JWT_SECRET: "c2VjdXJlYmFua19zZWNyZXRfa2V5X2Zvcl9qd3RfdG9rZW5fZ2VuZXJhdGlvbl8yMDI2"
