apiVersion: apps/v1
kind: Deployment
metadata:
  name: securebank-postgres
  namespace: securebank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securebank-postgres
  template:
    metadata:
      labels:
        app: securebank-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: securebank-secrets
          env:
            - name: POSTGRES_DB
              value: "securebank"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: securebank-postgres
  namespace: securebank
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: securebank-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securebank-zookeeper
  namespace: securebank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securebank-zookeeper
  template:
    metadata:
      labels:
        app: securebank-zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.6.1
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: securebank-zookeeper
  namespace: securebank
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: securebank-zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securebank-kafka
  namespace: securebank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securebank-kafka
  template:
    metadata:
      labels:
        app: securebank-kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.6.1
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "securebank-zookeeper:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://securebank-kafka:9092,PLAINTEXT_INTERNAL://securebank-kafka:29092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: securebank-kafka
  namespace: securebank
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: securebank-kafka
