server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: totp-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/securebank}
    username: ${SPRING_DATASOURCE_USERNAME:securebank}
    password: ${SPRING_DATASOURCE_PASSWORD:securebank_secret_pass}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}

totp:
  issuer: ${TOTP_ISSUER:SecureBank}
